### ISSUE TITLE
Suggesting: Outdated client error message should display instead of connection error message

### ISSUE THREAD

**Issue by FixTheAdmin** [WaterfallMC/Waterfall#307]
When connecting with an outdated client through waterfall (and bungeecord) the player is presented with the generic error message "Could not connect to default or fallback server...". I'd like it to display the error message with which server version is used and that the player has to upgrade/downgrade the client.

**Comment by BillyGalbreath** [comment]
As stated in Discord to you earlier today, it already does that..

![](https://i.valaria.pw/181116113235.png)

If it isn't for you, then you need to provide more information. You never answered the questions asked of you earlier, either.

![](https://i.imgur.com/aZPHacL.png)
![](https://i.imgur.com/QA65OGX.png)
