### ISSUE TITLE
Massive users kick

### ISSUE THREAD

**Issue by OakPrf2** [WaterfallMC/Waterfall#689]
I have a problem, which happens randomly, there are days that it does not happen and days that it does.

The problem is that most of the users that are playing get kicked (not all) from the server at the same time with the exception: [username] disconnected with: ReadTimeoutException: null

In the log of the spigot sv they are kicked for the reason: Timed out

What could the error be due to?

**Comment by electronicboy** [comment]
> ReadTimeoutException

The proxy didn't recieve any packets from the client within the past 30 seconds, stuff like this is generally networking issues, etc
