### ISSUE TITLE
UpstreamBridge - read timed out

### ISSUE THREAD

**Issue by TheDarthFather** [WaterfallMC/Waterfall#691]
Hello,
I have a small home server for my kids and their friends and moved from multiverse to waterfall recently.
Almoust every time we connect (from home or outside) we get the error below. 
The second or third try you can connect:
[19:04:51 WARN]: [/IP:27717|TheDarthFather] -> UpstreamBridge - read timed out
[19:04:51 INFO]: [TheDarthFather] disconnected with: ReadTimeoutException : null

I am using pterodactyl, with 

**Bungee:** 
Build: last build of waterfall and java 16.
Plugins: BungeeResourcePacks, LuckyPerms, ViaVersion
Config: [waterfall_config.zip](https://github.com/PaperMC/Waterfall/files/7246134/waterfall_config.zip)

**Survival Server:**
Build: Last 1.17.1 Paper build and java 16
Plugins (45): AdvancedPortals, AsyncWorldEdit, AuctionHouse, Autorank, BedWars, Blacksmith, Cannons, ChatInjector, Chunkmaster, Citizens, CMILib, CraftBook, DiscordSRV, dynmap, dynmap-structures, DynMapNPC*, EconomyShopGUI, EffectLib, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, GriefPreventionDynmap*, Jobs, LuckPerms, Magic, mcMMO, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, MythicMobs, ore-control, PlaceholderAPI, PlugMan, ProtocolLib, ResourceWorld, Sentinel, Slimefun, Statz, TNTRun_reloaded, Vault, WorldEdit, WorldGuard
Config: [Survival.zip](https://github.com/PaperMC/Waterfall/files/7246178/Survival.zip)

Do you have any hints ?

**Comment by TheDarthFather** [comment]
Ok, I did more investigations. 
It seems the Magic plugin resource pack that is loading at the beggining (as we jump directly to Survival) is causing this. 
What settings options do I have (besides not loading that ress pack ) ?
I assume is a setup to force join in hub first !? ..

**Comment by Janmm14** [comment]
try increase timeout and server_connect_timeout

**Comment by TheDarthFather** [comment]
I increased server_connect_timeout to 20k .. but I will do 90k ...  and also raise timeout thanks!
Closing ...
