### ISSUE TITLE
Typo in patch 0010

### ISSUE THREAD

**Issue by oldium** [WaterfallMC/Waterfall#697]
The following line should reference `dest` argument, not `chars`.

https://github.com/PaperMC/Waterfall/blob/85c0a35f0b40a12ff0d7a35c6ea31287eecab707/BungeeCord-Patches/0010-Optimize-uuid-conversions.patch#L54

**Comment by Janmm14** [comment]
There's another copypaste error here:
https://github.com/PaperMC/Waterfall/blob/85c0a35f0b40a12ff0d7a35c6ea31287eecab707/BungeeCord-Patches/0010-Optimize-uuid-conversions.patch#L82
