### ISSUE TITLE
Too many plugin message channels registered

### ISSUE THREAD

**Issue by ZeroG-Network** [WaterfallMC/Waterfall#701]
Hello
When I try to join my modded server I keep getting the ReadTimeoutException : null

I am one version lower than the latest also when I go into the latest it does not allow me to join with a modded client into the hub saying I have too many channels or something, https://mcpaste.io/696ab3f16751702b. 

How can I fix this issue?

kind regards
ZeroG Craft Co-Owner
MrWhiteFlamesYT

**Comment by PFilip08** [comment]
I get the same error (ReadTimeoutException : null).
Waterfall kicks player after 20-30 min, but with normal client, not modded.

**Comment by OPYHL** [comment]
I also have the same problem. Proxy console logs: UpstreamBridge - read timed out

**Comment by Xernium** [comment]
Your issue is unrelated @PFilip08 and @OPYHL 
This issue is caused because too many mod communication channels are used by the client. I’ll take a look at this size limit more thoroughly in a bit

**Comment by ZeroG-Network** [comment]
Thank you mate

**Comment by ZeroG-Network** [comment]
> 
> 
> Your issue is unrelated @PFilip08 and @OPYHL This issue is caused because too many mod communication channels are used by the client. I’ll take a look at this size limit more thoroughly in a bit

Also it is when I join hub, I get the ReadTimeoutException : null when I join the modded server.

**Comment by PFilip08** [comment]
> Your issue is unrelated @PFilip08 and @OPYHL This issue is caused because too many mod communication channels are used by the client. I’ll take a look at this size limit more thoroughly in a bit

Ok

**Comment by electronicboy** [comment]
Duplicate of #545
