### ISSUE TITLE
Chat and commands do not work on Paper server connected to Waterfall

### ISSUE THREAD

**Issue by VladOliinyk** [WaterfallMC/Waterfall#721]
My setup:
**1. Clean paper server (paper-1.18.1-136), no plugins or any changes except:** 
```
**spigot.yml**
> bungeecord: true
```

```
**server.properties**
> ip: 127.0.0.1
> port: 25561
> some minor stuff like rcon, notd, port. etc
```

**2. Clean Waterfall (waterfall-1.18-475), with only changed:**
```
**config.yml**
> host
> priorities
> servers
```

**3. (as a test) Clean BungeCord, with the same config.yml as Waterfall.**

**Test n1:**
When running the server separately from Waterfall/Paper - everything works fine.

**Test n2:**
When running the server in conjunction with Waterfall, problems begin. The server starts fine, I join the server fine too, but:
 
It's hard to explain exactly how this happens, but:
When a player (me) writes something in chat, pressing Enter should execute a command or send a text to in-game chat. But nothing happens. Chat seems to just close. There are no logs in the Paper server console, nor in the Waterfall console. There's just nothing. 

Also, do not work hotkeys on the type F3 + F4 (in fact it is a send command, but still).

**Test n3:**
I tried the same thing but with BungeeCord. The configuration is the same, however, everything works. Chat works, commands work. 

**Conclusion**
I hope it's something I did wrong and it's not a Waterfall problem, however, it looks exactly like the last option.

**Comment by Xernium** [comment]
Logs of both server and waterfall instance please. They must include the player joining.

**Comment by GuNanOvO** [comment]
I have a similar situation on my server. When the waterfall and sub-server are started, everything works fine for a while, but after a while, the joinmessage and chat have problems one after another. I can't see the chat from sub-server 2 on sub-server 1 (I installed the cross-server chat plugin), and I can't see the global join message on sub-server 1. But on sub-server 2, chat messages from sub-server 1 can be seen. But on sub-server 2, you can only see the join messages of other players but not your own. I don't know how this all happened, I'm confused, I didn't find any error log on subserver with waterfall. When all this error happens, I use command /glist in waterfall console, it shows that there are many players with the same name in subserver, but using command /list in corresponding subserver console does not have these duplicate players, all this Like a ghost, but when I just restart waterfall, everything works again. My English is not good, I'm using google translate.

**Comment by GuNanOvO** [comment]
![image](https://user-images.githubusercontent.com/63027311/148652128-cd667fe4-4583-4b95-ad90-981cc90d8b50.png)
Duplicate players appear in waterfall, but not on subservers.

**Comment by VladOliinyk** [comment]
> Logs of both server and waterfall instance please. They must include the player joining.

**As I wrote, there is nothing on logs**, btw here they are:
Waterfall: https://pastebin.com/E19LTSBj
Paper server: https://pastebin.com/088t6ryZ

After successful connection to the server, as a player on a server, I was trying to enter commands, try to send something in chat. Nothing happened.  Then, I send "hello?" from the server console. It displayed well. But from the player side - there is nothing.

**Comment by VladOliinyk** [comment]
**ck me, guys!
The damn [AuthMeBungee](https://github.com/AuthMe/AuthMeBungee) was in the waterfall plugins folder.

So, I've deleted that not configured plugin, and all works fine.

I feel so dumb now. 

Anyway, @sgdc3 is there a way you could somehow maybe enable the logs for the [AuthMeBungee](https://github.com/AuthMe/AuthMeBungee) plugin in the Waterfall console?

**Comment by VladOliinyk** [comment]
@shkipan test

**Comment by sgdc3** [comment]
@VladOliinyk AuthMeBungee cancels any chat message/command from any unlogged player, you probably misconfigured AuthMe or AuthMeBungee. Make sure that both plugins are installed in your network (AuthMe in your lobbies, AuthMeBungee in the proxies). Make sure that the "bungeecord" option is enabled in your spigot.yml files! 😃

**Comment by VladOliinyk** [comment]
> @VladOliinyk AuthMeBungee cancels any chat message/command from any unlogged player, you probably misconfigured AuthMe or AuthMeBungee. Make sure that both plugins are installed in your network (AuthMe in your lobbies, AuthMeBungee in the proxies). Make sure that the "bungeecord" option is enabled in your spigot.yml files! 😃

@sgdc3 Thanks for the detailed response! Sure! My problem was that I just completely forgot that the AuthMeBungee.jar plugin file was in the plugins folder. So I even do not think checking that folder. And that’s why the problem exist. The server-side plugin has not even been installed.

Again, thanks for your time and I apologize for taking it away for such a (seemingly) insignificant thing :)
