### ISSUE TITLE
Can't join waterfall/papermc with mods installed on client

### ISSUE THREAD

**Issue by OzServer** [WaterfallMC/Waterfall#723]
As the title says I have a paper-1.18.1-140 hub server running on waterfall-1.18-473 bungee

I want to run a modded server off the hub server but unfortunately alot of the mods I want to use won't let my client join the papermc hub serve
![setoftags](https://user-images.githubusercontent.com/97483850/148852744-fa1202fa-fa74-4848-a735-4f4a9125e16c.png)
r

I get this error whenever I try to join

I understand it would fix if I change the hub server to a forge server but I have a survival world connected to the hub also

so that is not an option for me.

Any help would be greatly appreciated

**Comment by electronicboy** [comment]
the mods need to exist on the server when you connect so that all of the info from the server is sent and matches up with what the client expects, there is pretty much nothing we can do here

**Comment by Xernium** [comment]
See #450 
Forge above 1.12.2 isn’t supported.
