### ISSUE TITLE
Entity metadata/tablist rewrite

### ISSUE THREAD

**Issue by andreasdc** [WaterfallMC/Waterfall#725]
disable_entity_metadata_rewrite
disable_tab_list_rewrite
What enabling these option really do? I couldn't find exact information is it safe, does it impact performance etc.

**Comment by Arobcher** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by electronicboy** [comment]
Bungeecord rewrites all entity metadata and tab list packets, those options allow you to disable that feature

The feature itself is safe and is based upon the way the modern client works, it has some caveats, but is generally safer in terms of how it treats the client and improves performance of the proxy itself
there have been some plugin compat issues, but many of those have been fixed over the years

**Comment by andreasdc** [comment]
> Bungeecord rewrites all entity metadata and tab list packets, those options allow you to disable that feature
> 
> The feature itself is safe and is based upon the way the modern client works, it has some caveats, but is generally safer in terms of how it treats the client and improves performance of the proxy itself there have been some plugin compat issues, but many of those have been fixed over the years

Isn't it better to keep it enabled by default?

**Comment by electronicboy** [comment]
disabling that stuff by default would be a behavioral change, I have considered it over the years but have been wary as there has been a break or two over the years

**Comment by andreasdc** [comment]
> caveats

What are these? I want to have the fastest and the smoothest server, will it help in any way?

**Comment by electronicboy** [comment]
that's of a technical nature and this is not the place for discussions

**Comment by andreasdc** [comment]
> that's of a technical nature and this is not the place for discussions

I'm sure this issue will be helpful in the future for anyone who will be interested in better explanations of these options. If it doesn't break or make anything worse, I take it. Thanks for answers.

**Comment by andreasdc** [comment]
> that's of a technical nature and this is not the place for discussions

But is it possible that I observe worse smoothness after enabling it?

**Comment by electronicboy** [comment]
This is not the place for back and forth discussions, I and many others don't need our emails being flooded with such back and forths

disabling metadata rewriting may impact switching worlds and cause the process to take longer as it resets a good chunk of stuff on the client, but otherwise it's gonna reduce the amount of work that the proxy does
