### ISSUE TITLE
Adding packet limiter 

### ISSUE THREAD

**Issue by msmanui** [WaterfallMC/Waterfall#726]
As far as im concerned, paper team is not recommending using packet-limiter in paper.yml when is running under a proxy. 
My suggestion would be adding a packet limiter built-in directly in Waterfall as i can not really find a packet limiter plugin for a proxy.

**Comment by Janmm14** [comment]
use viaversion packet limiter then, its per player

**Comment by msmanui** [comment]
> use viaversion packet limiter then, its per player

Installing viaversion in bungee just for the packet limiter? You cant just disable other featueres and leave only packet limiter

**Comment by Janmm14** [comment]
I mean install on paper, not on waterfall.

**Comment by msmanui** [comment]
> I mean install on paper, not on waterfall.

Paper team doesnt recommend using packet-limiter in the spigot when you have a proxy... Thats why im suggesting to add a packet limiter in the waterfall

**Comment by Janmm14** [comment]
I do not get the reason of the paper team then. bungee/waterfall usually doesn't do much with the packets, so limiting them on the proxy does not create huge advantages in my eyes.

**Comment by electronicboy** [comment]
No idea who said that

**Comment by xism4** [comment]
> As far as im concerned, paper team is not recommending using packet-limiter in paper.yml when is running under a proxy. My suggestion would be adding a packet limiter built-in directly in Waterfall as i can not really find a packet limiter plugin for a proxy.

I don't know if this is the best option, for x reason you can send more packets and get kicked out.
Any ways the max Uncompressed bytes are 2mb (2097152)

**Comment by xism4** [comment]
> As far as im concerned, paper team is not recommending using packet-limiter in paper.yml when is running under a proxy. My suggestion would be adding a packet limiter built-in directly in Waterfall as i can not really find a packet limiter plugin for a proxy.

I have studied more BungeeCord itself during this year. There seems to be a lot of byte limits per packet (e.g. the handshake) just fine. You could end up limiting some more like in Velocity, but that would be for a pull-request.

**Comment by Arobcher** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xism4** [comment]
> ### This comment was marked as spam.
> Show comment

Yes i totally agree.

**Comment by Janmm14** [comment]
> > ### This comment was marked as spam.
> > Show comment
> 
> Yes i totally agree.

Replying to spam is never a good thing.
In my opinion, this issue should be closed.
