### ISSUE TITLE
Rest API of spark blocked by waterfall

### ISSUE THREAD

**Issue by einfachBlu** [WaterfallMC/Waterfall#727]
Hey, i have a plugin that initializes a RestAPI with Spark. I can access that rest api if i use BungeeCord, but not when using Waterfall. The connection just timed out. In Waterfall Console is nothing showing up, no error or exception. it just blocks incoming traffic (as it seems)

i have tested it with default generated bungeecord and waterfall config.

- Java 16
- Build 480
- Linux Ubuntu 20.04.3 LTS

**Comment by electronicboy** [comment]
waterfall doesn't have any logic which would explicitly do that, timing out would generally imply an environment aspect, i.e. routing, but, god knows

**Comment by einfachBlu** [comment]
idk why its happening to waterfall, but it does somehow. if i use the exact same environment but with waterfall, its not working as it does when using bungeecord

**Comment by electronicboy** [comment]
We'd need more info or something, reliable replication, etc, etc; there's nothing for us to work from here

**Comment by einfachBlu** [comment]
replication is simple:

- initialize a Spark Rest Server with a GET hello-world listener and try to access it from the browser

**Comment by einfachBlu** [comment]
Example Code:

```java
Spark.port(15000);
Spark.get("/hello", (request, response) -> {
  return "received, its working";
});

Spark.awaitInitialization();
```
```java
compile "com.sparkjava:spark-core:2.9.3"
```

Url: localhost:15000/hello

**Comment by einfachBlu** [comment]
Okay, i have found the bug. It was my fault. The listener was blocked async, because i tried to acces the proxy.log.0 file, which does exist in bungeecord but not in waterfall
