### ISSUE TITLE
did you forget to enable BungeeCord in spigot.yml?

### ISSUE THREAD

**Issue by Timtaran** [WaterfallMC/Waterfall#729]
`Kicked whilst connecting to survival: Unknown data in login hostname, did you forget to enable BungeeCord in spigot.yml?`
spigot.yml:
```
settings:
  debug: false
  bungeecord: true
```

**Comment by pengGgxp** [comment]
How did you solve it?

**Comment by Janmm14** [comment]
> How did you solve it?

Try to remove plugins until it works. Make sure server ip is correct in bungee settings, bungee is updated and has it enabled as well, etc etc
