### ISSUE TITLE
Bad packet ID

### ISSUE THREAD

**Issue by PadowYT2** [WaterfallMC/Waterfall#730]
I have a `InitialHandler - bad packet ID, are mods in use!? No more bytes reading varint` error. It slowes down my router to a restart of it, I'm getting [a lot of it](https://haste.padow.ru/ugirayiciq). What causes it & is there a way to completly stop this? The ip's are banned with banip with AdvancedBan btw.

Plugins (on proxy ofc):
Advanced-Portals-0.9.2.jar
AdvancedBan-Bundle-2.3.0-RELEASE.jar
AntiBot.jar
AuthMeBungee-2.2.0-beta1.jar
BungeecordPartyAndFriends-1.0.86.jar
BungeeGuard.jar
BungeeHub.jar
CommandSyncServer.jar
FallBackServer-2.1.1.jar
Geyser-BungeeCord.jar
LuckPerms-Bungee-5.3.98.jar
minimotd-universal-2.0.5.jar
Retribution.jar
SkinsRestorer.jar
protocolize-bungeecord.jar

**Comment by Xernium** [comment]
Waterfall is doing what its designed to do. You can probably use a plugin that provides a log filter or a plugin that changes how new connections are handled. Otherwise this isn’t a Waterfall issue.

**Comment by PadowYT2** [comment]
👍
