### ISSUE TITLE
Outdated protobuf version

### ISSUE THREAD

**Issue by luiz-otavio** [WaterfallMC/Waterfall#733]
I took a look in waterfall dependencies and I found that `protobuf-java` is running on `3.11.4` version, which was released in `2019`.
![image](https://user-images.githubusercontent.com/65752397/163444164-f1daf9d3-8606-46b0-a0fc-6a978d4e464f.png)
Because of that outdated version, some issues like [that](https://github.com/protocolbuffers/protobuf/issues/9236) happens everywhere.
I realize this is due to transitive dependencies, but I haven't seen any of them. I mean, we could "strictly" an updated version to fix this.

**Comment by portlek** [comment]
same issue here https://github.com/PaperMC/Paper/issues/7782

**Comment by electronicboy** [comment]
This is the version promised by the API for bungeecord, I may look at updating the MySQL driver but this is not really an issue, relocate and shading your own dependencies is generally the best path here
