### ISSUE TITLE
Connect to server - [playername] disconnected with: EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125

### ISSUE THREAD

**Issue by LutrexMC** [WaterfallMC/Waterfall#735]
You will be kicked from the bungeecord server if you try to join a server with /server.

The lobby is on version 1.8.8

The bungee cord has the latest version

And the server I want to connect to is on the 1.12.2

I sent the log where the error is

[latest.log](https://github.com/PaperMC/Waterfall/files/8521342/latest.log)
.

**Comment by electronicboy** [comment]
Reproduce without plugins, something caused an invalid tab completion response to be generated

**Comment by LutrexMC** [comment]
What could be the reason? I have installed the following plugins:
![grafik](https://user-images.githubusercontent.com/74796414/164228553-b7026e2b-fb7c-437e-a9a8-8bb03aa0c404.png)

**Comment by electronicboy** [comment]
as I said, something is generating an invalid tab response packet to be sent to the client, there is no viable path for this to occur in the proxy itself that I can see

**Comment by LutrexMC** [comment]
overflow in packet detected! A string had more data than allowed. For more information, launch Waterfall with -Dwaterfall.packet-decode-logging=true 

This message came on the 1.12.2 server.
