### ISSUE TITLE
Bypass restricted servers with forced_hosts

### ISSUE THREAD

**Issue by LuckCrafter** [WaterfallMC/Waterfall#738]
I have both restricted and forced_hosts enabled. I use LuckPerms to assign the permission. I use resticted (bungeecord config) as a whitelist replacement. However I noticed when I use forced_host e.g. s1.domain.net : server1
it is not checked if i have the permission for it but i am redirected to the server if possible instead of landing in the lobby.

**Comment by electronicboy** [comment]
This is 100% intended behavior for bungeecord
