### ISSUE TITLE
Can't type in the console after closing

### ISSUE THREAD

**Issue by andreasdc** [WaterfallMC/Waterfall#739]
Almost everytime after closing Waterfall, when I'm pressing arrows on the keyboard to run it again, I have this instead of previous commands: 
> # ^[OA^[OA^[OB^[OA^[OB^[OD

I have to kill the screen and create it again.

**Comment by Xernium** [comment]
Not a Waterfall issue. The terminal Interfaxe you’re using has an info (terminfo) mapping that’s causing this. You will be able to fix this issue by googling for these scancode characters.
Keep in mind that this functionality, which includes the DEL key is part of the extended terminal features, so you’ll have a harder time if you’re using something like Windows builtin CMD or Powershell to access it.

**Comment by andreasdc** [comment]
> Not a Waterfall issue. The terminal Interfaxe you’re using has an info (terminfo) mapping that’s causing this. You will be able to fix this issue by googling for these scancode characters. Keep in mind that this functionality, which includes the DEL key is part of the extended terminal features, so you’ll have a harder time if you’re using something like Windows builtin CMD or Powershell to access it.

But it doesn't happen all the time, I use linux btw.

**Comment by Janmm14** [comment]
When there is a problem after waterfall completely shut down it cannot be a problem of waterfall.
Maybe waterfall was not completely shut down when you tried?

**Comment by andreasdc** [comment]
> When there is a problem after waterfall completely shut down it cannot be a problem of waterfall. Maybe waterfall was not completely shut down when you tried?

Depends if 'end' is closing waterfall.

**Comment by Janmm14** [comment]
> > When there is a problem after waterfall completely shut down it cannot be a problem of waterfall. Maybe waterfall was not completely shut down when you tried?
> 
> Depends if 'end' is closing waterfall.

Did you see "Thank you and goodbye" in console before your attempts of arrow key usage fails?

**Comment by andreasdc** [comment]
> > > When there is a problem after waterfall completely shut down it cannot be a problem of waterfall. Maybe waterfall was not completely shut down when you tried?
> > 
> > 
> > Depends if 'end' is closing waterfall.
> 
> Did you see "Thank you and goodbye" in console before your attempts of arrow key usage fails?

Yes I see that.
