### ISSUE TITLE
Glist error

### ISSUE THREAD

**Issue by z0z0r4** [WaterfallMC/Waterfall#740]
![55V12PQJZB OU 3@9WST$M](https://user-images.githubusercontent.com/78744121/168463647-471e9047-d7b3-4c74-a0c4-bbc909f1ca55.png)
![YURYG(E4P6 0$OCHWX5S1)N](https://user-images.githubusercontent.com/78744121/168463670-37d76c02-ec8f-46a5-871b-af7a6533796d.png)

0+0+17+0=18?? These player number not right

version: waterfall-1.18-483

**Comment by z0z0r4** [comment]
But after I restarted all servers...
![image](https://user-images.githubusercontent.com/78744121/168463739-422c09c3-6489-4755-8e68-7c59040589b5.png)
I don't know why

**Comment by xism4** [comment]
> But after I restarted all servers...

 It could be just an normal delayed thingy, like he just leaved or smth like that. Nothing as a bug.
