### ISSUE TITLE
Command Execution Error

### ISSUE THREAD

**Issue by gamingcodedev** [WaterfallMC/Waterfall#748]
If i execute an bungeecord command, like my own writen /ban command there also execute that command on bukkit.

https://prnt.sc/h_k1AZpKlXrm

same like /bungee or something else:

https://prnt.sc/CNUZsq3dOyUn

**Comment by Luccboy** [comment]
This should be fixed with the newest upstream update (https://github.com/PaperMC/Waterfall/commit/e4f1e3ff8d1b6ec226c3f1e00e5b0c495d9f9b6a)

**Comment by gamingcodedev** [comment]
thx it works!
