### ISSUE TITLE
Spectator mode has collision

### ISSUE THREAD

**Issue by Vooperino** [WaterfallMC/Waterfall#750]
Upon testing out the waterfall build of **493** and **490** it seemed that Spectator mode has gotten a collision where in default cases it should be no collision what so ever like noclip. 
After testing on a stable server running on 1.18.2 without the latest versions of waterfall spectator mode should work how it was, but after slapping on 1.19 update of the waterfall, when spectator mode just breaks.

After downgrading waterfall to a later versions the issues seemed to be gone.

**Comment by Xernium** [comment]
Your player UUID is desynced. Ensure the bungee-online-mode setting in the paper.yml reflects the bungee-online-mode and that forwarding is enabled. If that doesn’t help please turn off tab-list rewriting in the waterfall.yml

**Comment by Xernium** [comment]
The issue has now surfaced because of the player keys. This is a wont/cantfix and is a design-flaw in bungee we cant correct due to how the system works.
