### ISSUE TITLE
[Bungee] [Waterfall] [1.19 Spigot Server] Internal Exception: io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by Hax100** [WaterfallMC/Waterfall#751]
When I am in the 1.18.2 lobby and I execute the command "/server UpdatedSurvival" to go to 1.19 survival server, it does not work.
Obviously, I have via versions and stuff all set up but it keeps disconnecting me with this error. 
`[12.06 11:03:12] [Disconnect] /xxx.xxx.xxx.has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)`

**Comment by electronicboy** [comment]
We do not provide support for environments running protocol hacks, make sure that you're using the latest version of waterfall (495, at the time of writing)

**Comment by Hax100** [comment]
so.. who does provide support for "environments running protocol hacks"?

**Comment by electronicboy** [comment]
Generally the people whose protocol hacks you're using; All we can see is that apparently you got a mangled packet, and bungee doesn't log out such info

**Comment by Hax100** [comment]
i am not even sure what "protocol hacks" I am using lol. do you mean the ProtocolLib plguin? I contacted them already, but they don't know how to solve it, they need "further stack trace" and there is no error other than that one error I sent.

**Comment by electronicboy** [comment]
I mean viaversion, plugins on the server sending packets can also cause issues, etc; bungee explicitly cuts off the stack trace, so there's no sane means to get it without attaching a profiler or something

**Comment by Hax100** [comment]
so my only solution is the attach a profiler and do a stack trace then send that to viaversion support and they might have a solution?

**Comment by electronicboy** [comment]
That's basically the only means of finding the actual exception and what packet, etc, blew up while being read, without modifying the proxy itself to actually print out that info

**Comment by Hax100** [comment]
EDIT: ok i figured it out.
