### ISSUE TITLE
Skins and players are not displayed

### ISSUE THREAD

**Issue by YourRapiddeath** [WaterfallMC/Waterfall#753]
I already wrote it in the discord but I think it's better off here.

I noticed that no skins are displayed in Waterfall #495. No matter which version I connect to, it remains a Steve Skin. Also, you can't see other players. I've tried several variants.

Waterfall 1.19 --> Version 1.18.2 Server = No Skin
Waterfall 1.19 --> Version 1.19 Server = No Skin
Waterfall 1.18. --> Version 1.18.2 Server = has skin
The subservers are always the same and have not been changed

If I log in from both versions at the same time on a sub-server with two users, the older version has the skin, but the newer version doesn't. I hope you understand what I mean. 

greeting YourRapiddeath

**Comment by electronicboy** [comment]
Cannot reproduce, nor are protocol hacks supported; many issues akin to this are down to the tablist rewriting in bungee, and various other issues, you can disable tab list rewriting in waterfall.yml
