### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by WongIong** [WaterfallMC/Waterfall#756]
![image](https://user-images.githubusercontent.com/36799194/173940483-14a4b335-2c84-4063-bd89-c9294f8d946a.png)

**Comment by electronicboy** [comment]
This gives us nothing to go off, all we can see is that something mangled a packet, generally, reproduce without plugins, etc

**Comment by WongIong** [comment]
i think it is caused by Parties plugin, will report here when i get response from author
