### ISSUE TITLE
1.19 clients can not write sign text in 1.15 servers

### ISSUE THREAD

**Issue by Thorinwasher** [WaterfallMC/Waterfall#757]
Using waterfall 1.19-496 and a CraftBukkit version git-Spigot-3b314f5-e2790ae (spigot-1.15). When connecting to waterfall with a 1.19 client, a player can not write text on signs. The behavior follows this:
- Player places sign
- The write sign mode is engaged
- The write sign mode instantly disengages, leaving an empty sign

**Comment by electronicboy** [comment]
Protocol hacks are unsupported
