### ISSUE TITLE
Waterfall With Mohist

### ISSUE THREAD

**Issue by Smurfboi007** [WaterfallMC/Waterfall#759]
This is the error that shows up when trying to connect to the Mohist server from another server from the Bungeecord network:
"**The server you were previously on went down, you have been connected to a fallback server**"

(When I connect I use the right mod packs and version of forge)

My main servers are running 1.18.2 this one is 1.12.2. (Using Via Version and Via Backwards)

Works when directly connecting to the Mohist server but not through Bungeecord.

Here is the error on the proxy: https://pastebin.com/0fBsrhGF

**Comment by Xernium** [comment]
Mohist is unsupported. Youre also running an outdated version.
Though, it might fix itself if you disable tab-list and entity-meta rewriting in the waterfall.yml.
