### ISSUE TITLE
data still loaded error

### ISSUE THREAD

**Issue by iSeitan** [WaterfallMC/Waterfall#761]
We updated waterfall and viaversion on our network last week to the version 1.19-497 and since then player get randomly this error

disconnected with: Kicked whilst connecting to hub: Your data is still loaded, please rejoin in a moment.

It happens randomly on random player not all, either when the server restart and often when the player disconnect on himself
it happens on our whole network, thats why we think it might be waterfall

We made a binary search of our plugin to see if it would fix the issue with no luck

Happens on everyserver on the proxy even those with different plugin
The error either disappear when restarting the server, or randomly alone...

We cant figure it out its been more than a week we dont know what to do and we seem to be the only one cause we cant find anything on the web/issue/support discord..

any idea why that is?

**Comment by Janmm14** [comment]
Maybe #604?

**Comment by Janmm14** [comment]
"Your data is still loaded" is not a message bungeecord or waterfall create.
This seems to be a problem of a plugin on your hub server.

**Comment by iSeitan** [comment]
this issue happens on every server we have on our network randomly, but we still tried to remove our plugin but this error happened anyway
We tried the binary search without success

im not saying waterfall is creating this error, im saying it might be a vanilla error when a data is not saved correctly
If waterfall/papermc doesnt save/load data correctly this error would show right?

it couldnt be linked to our hub because it happens on other server as well
it couldnt be linked to a plugin because it happens when theres no plugin too

only thing we see is the proxy, since the issue arrived at the same time we updated waterfall to the 1.19 update #497

**Comment by Janmm14** [comment]
If vanilla wouldve contained this message it'd be googleable, but there is no result on google.

Paper source code on github doesn't contain this message.
In general the "please ..." part does not sound like a message mojang, spigot or paper would ever put in.
They'd use different wording and no "please". Also they'd likely wait while unloading & reloading the data instead of kicking.

**Comment by iSeitan** [comment]
i dont understand then... without plugin the error is still there..

**Comment by iSeitan** [comment]
Im out for the day, tomorrow il restart the whole process in case i missed something, thanks! :)

**Comment by Janmm14** [comment]
Maybe you could provide plugin lists and versions of both waterfall and one server where this is happening. Maybe this would be better suited for the Paper forims tho, not sure what paper wants in their issues and what not.

**Comment by electronicboy** [comment]
The kick came from the server, not the proxy; We have literally 0 control over what the servers do, nothing has changed with how the proxy works either, only real caveat of bungee, which has been the case for years, is that you'll join the new server before you leave the old one, which can create very fun interesting issues for plugins which don't handle that too well
