### ISSUE TITLE
TAB Complete is broken when 1.13+ clients try to use it via proxy server

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [WaterfallMC/Waterfall#763]
Using 1.8-1.12 MC client, joining Waterfall proxy server, you can only tab complete commands that are:
- registered on the proxy server
- that player has permission to execute

Using 1.13+ MC client, joining Waterfall proxy server, you can tab complete ANY command ever registered on proxy server despite any permissions

Please test this because this is serious bug

**Comment by electronicboy** [comment]
Cannot reproduce, there are some nuances here, however; post 1.13, the way commands work in the server changed, and now the proxy needs to send all commands that the player can access to the client, this is done by injecting into the command structure packet sent by the server to add such entries

bungeecord, and by extension, waterfall, will add all of the commands which the player apparently has access to, this is 100% reliant on plugins handling command execution access properly, and won't refresh until they relog, or switch servers (or do something which induces the server to resend commands)
