### ISSUE TITLE
Every bungeecord message sent in actionbar message

### ISSUE THREAD

**Issue by Marcy15** [WaterfallMC/Waterfall#766]
Hi! When i receive a bungeecord message example: /server /gist /staffchat(it's custom plugin) it send in actionbar.
![kép](https://user-images.githubusercontent.com/59490469/179375246-43a6e84e-f1b7-43c2-a7b8-8847d24ac794.png)
My waterfall version: waterfall-1.19-498

**Comment by Marcy15** [comment]
At my network in Lobby and BuildFFA servers like this. The other's are normally work.

**Comment by Janmm14** [comment]
Update your ViaVersion everywhere.
