### ISSUE TITLE
readAddress(..) failed: Connection reset by peer &  Unexpected packet received during server login process! 3604018078fad2a60839778bbb3370a5

### ISSUE THREAD

**Issue by Marcy15** [WaterfallMC/Waterfall#768]
Hi! Some of my players get this error. Just a a small percent.

![kép](https://user-images.githubusercontent.com/59490469/179403302-51f547dd-5e6a-4320-b68e-57007fff6d83.png)

AND some players get this error:
 disconnected with: Exception Connecting:QuietException : Unexpected packet received during server login process!
3604018078fad2a60839778bbb3370a5

**Comment by Janmm14** [comment]
Connection reset by peer is not fixable, its the other end closing the connection.
And unexpected packet bla is often also not a minecraft client trying to connect

**Comment by Marcy15** [comment]
`And unexpected packet bla is often also not a minecraft client trying to connect`

This error is for same players. Use official minecraft client.

**Comment by electronicboy** [comment]
There is nothing useful here for us to go off, generally something on the server sent a mangled packet, check server logs/reproduce without plugins, for support, please use the discord/forums
