### ISSUE TITLE
StatusRequest CorruptedFrameException

### ISSUE THREAD

**Issue by Nononitas** [WaterfallMC/Waterfall#773]
I sometimes get those error and I have no idea why https://pastebin.com/RRqNHnzA
This error didn't occured with using lower version than Build 496
I am using Waterfall Build 501

**Comment by electronicboy** [comment]
Theres not really much we can say on this unless you know what's opening the connection; All we can see is that something tried to apparently send an illegal packet to the proxy, version is likely irrelevant, given that pretty much nothing has changed around this; stuff like this is often traced back to random bots tryna scour the web and doing weird things like sending HTTP traffic over random ports

**Comment by Nononitas** [comment]
Ok good to know thank you.
