### ISSUE TITLE
/server not working

### ISSUE THREAD

**Issue by skaaiya** [WaterfallMC/Waterfall#778]
So been a few days I am getting an issue where I cannot use the /server command, how can i fix this?

**Comment by MiniDigger** [comment]
whats the output if you run that command?

**Comment by skaaiya** [comment]
''You do not have the permission to execute this command!'', even tho I have op

**Comment by electronicboy** [comment]
The proxy doesn't know or care that you have op, you need to setup the perms on the proxy, if you installed a perm plugin on the proxy, you'll need to grant yourself perms through that https://www.spigotmc.org/wiki/bungeecord-commands/

**Comment by MiniDigger** [comment]
the command is run on the proxy, you need to have the perms on the proxy. please look at the config.yml or your proxy perm plugin

**Comment by skaaiya** [comment]
> 

ok thanks
