### ISSUE TITLE
Hello im getting a error Could not connect to a default or fallback server. Incorrectly configured address/port/firewall?  

### ISSUE THREAD

**Issue by gigantickey980** [WaterfallMC/Waterfall#780]
My Config https://pastebin.com/vGvQbENZ Please help i rlly need it

**Comment by electronicboy** [comment]
The issue tracker is not the place for support with configuration issues. The ip/port combo also suggests a shared host, in which case, you'd be best speaking to them for support

**Comment by gigantickey980** [comment]
> 

I talked with them before coming here but they said they dont know how to use waterfall so whats the issue can ik and ask them to sort it out?

**Comment by electronicboy** [comment]
I can't see what the issue is without your logs, this is not the correct place, but, 99% of those issues are down to network configuration/routing. If you're using a MC host, I'd suggest finding another company.

**Comment by gigantickey980** [comment]
> 

Well my logs as in console logs?

**Comment by electronicboy** [comment]
This is not the place for support, please use the discord/forums/IRC

**Comment by gigantickey980** [comment]
paper discord right?

**Comment by electronicboy** [comment]
Yes
