### ISSUE TITLE
[/127.0.0.1:25565] <-> InitialHandler - read timed out

### ISSUE THREAD

**Issue by Rockin21** [WaterfallMC/Waterfall#785]
[11:33:03 WARN]: [/127.0.0.1:25565] <-> InitialHandler - read timed out

This error keeps spamming my console, not much more to detail. 

Version: 1.19 build 507
Plugins:
BungeeGuard, FallBackServer, Geyser-BungeeCord, LuckPerms, MiniMOTD, NuVotifier, Plan, Protocolize, ServerUtils, TCPShield, UltraStaffChatPro, floodgate and spark

![Capture](https://user-images.githubusercontent.com/110613392/205371774-4385244a-c5d8-4c7a-a3e1-eac16d46ae53.PNG)

**Comment by electronicboy** [comment]
Read timed out just says that no packets were received from the connection in 30 seconds, you'd need to work out what the source of that connection is and work out why
