### ISSUE TITLE
1.18.2 forge cannot be used successfully

### ISSUE THREAD

**Issue by DSword91** [WaterfallMC/Waterfall#786]
Hi！ I have some problems with 1.18.2forge server.

waterfall core display :This server has mods that require Forge to be installed on the client. Contact your server admin for more details.

Downstream server display :Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.

Client 1.18.2forge version :40.1.80
Server 1.18.2forge version :80

The server and client modules are consistent.

How can we solve this problem?

**Comment by xism4** [comment]
> Hi！ I have some problems with 1.18.2forge server.
> 
> waterfall core display :This server has mods that require Forge to be installed on the client. Contact your server admin for more details.
> 
> Downstream server display :Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.
> 
> Client 1.18.2forge version :40.1.80 Server 1.18.2forge version :80
> 
> The server and client modules are consistent.
> 
> How can we solve this problem?

Waterfall does not support modern forge, use some fork like ligthfall (depends on a client mod) to run 1.13+ fml
