### ISSUE TITLE
QuietException when joining the Proxy

### ISSUE THREAD

**Issue by Nononitas** [WaterfallMC/Waterfall#787]
If you join the Proxy you will get kicked with this error
net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
6701116d696e6563726166743a76616e

This only occurs on Build 510, on 509 the bug doesn't occur

Join a 1.19.2 Server using ViaVersion with a 1.19.3 Client

Using Waterfall-510 with no plugins installed
Client (Vanilla) 1.19.3
Backend server: 1.19.2 (Paper-304) with newest ViaVersion

**Comment by electronicboy** [comment]
Use the dev builds of viaversion
