### ISSUE TITLE
InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 4554202f736f636b65742e696f2f3f45

### ISSUE THREAD

**Issue by Dark2932** [WaterfallMC/Waterfall#788]
I don't know what happened, but when I use Waterfall on my server, it throws this error.
It doesn't happen when player login, player can login successfully.
Only happen when I start Waterfall.

console screenshot:
![image](https://user-images.githubusercontent.com/72404859/213619223-f2ff6db1-842c-4878-ae4c-ad115ac3a414.png)

**Comment by electronicboy** [comment]
You have something sending HTTP requests to your proxy instance
