### ISSUE TITLE
Index Out of Bounds exception

### ISSUE THREAD

**Issue by hotspuraz** [WaterfallMC/Waterfall#794]
Running version 1.19-515 I get this error in the console when players attempt to join using a 1.19.4 client: https://pastes.dev/B5f9HtGw8D - this issue also existed on 1.19-514.

It seems like a few others are having the same problem, but I couldn't find a solution on discord. This may be a BungeeCord issue which needs to be updated on their end.

**Comment by l3nnartt** [comment]
Use the latest version

**Comment by hotspuraz** [comment]
1.19-515 is the latest version my guy, I waited for the release for this reason but the problem has persisted :/

`This server is running Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515 by md_5`

**Comment by electronicboy** [comment]
Run the proxy with `-Dwaterfall.packet-decode-logging=true` (before -jar) to get the full exception, 99% of issues like this are either bungee issues or plugins messing with networking stuff

**Comment by hotspuraz** [comment]
Same issue, but with more detailed error logs: https://pastes.dev/g037Le17um

Turns out it's BungeePackFix for ItemsAdder causing the issues. Extra flags helped diagnose the problem 👍
