### ISSUE TITLE
FastDecoderException on 1.19.4 Proxy with 1.19.3 ViaVersion Backend

### ISSUE THREAD

**Issue by ItzFlipp** [WaterfallMC/Waterfall#795]
Hello. Upon updating to Waterfall build 515 (1.19.4 support), any player connecting to my 1.19.3 ViaVersion backend server through my proxy on 1.19.4, they are kicked immediately with the error:   https://mcpaste.io/e27f804750c0d2d3

The player is kicked with the kick message: "The server you were previously on went down, you have been connected to a fallback server."

I contacted ViaVersion about this issue, and they told me it was a Waterfall issue. My ViaVersion is up to date (git-ViaVersion-4.6.1-SNAPSHOT:18b41c82, git-ViaBackwards-4.6.1-SNAPSHOT:11e71b1)

Thank you in advance.

**Comment by electronicboy** [comment]
> at dev.lone.bungeepackfix.bungee.packets.impl.ClientboundResourcePackPacket.read(ClientboundResourcePackPacket.java:96) ~[?:?]

This is a plugin issue
