### ISSUE TITLE
Unknown system variable 'transaction_isolation'

### ISSUE THREAD

**Issue by EpicJosch** [WaterfallMC/Waterfall#810]
It seems the mysql jdbc connector that is included in waterfall is depracated. When using it with the newest mariadb database version it throws the error (Unknown system variable 'transaction_isolation').

Waterfall: waterfall-1.20-536
Database: mariadb:latest

**Comment by electronicboy** [comment]
It's not a deprecation issue, it's a "mariadb isn't compatible with the mysql driver" properly, given that both drivers break support for stuff on one another, it's not exactly a trivial fix bar downgrading the driver which feels bleh. the next .1 of mariadb fixes this
