### ISSUE TITLE
using ipv6 in waterfall config

### ISSUE THREAD

**Issue by adelando** [WaterfallMC/Waterfall#811]
Hello,

Im trying to use an ipv6 address in the waterfall config file but it errors out in console.

I have a test bed paper server that can only port forward on ipv6, but waterfall cannot process the ":" in an ipv6 address

**Comment by Seremptos** [comment]
try writing it like that :  "[youripv6address]" quotes included

**Comment by adelando** [comment]
thanks for your suggestion but this is the error i get now,

`09.08 17:09:35 [Server] [WARN] Error occurred processing connection for LeftRightShift AnnotatedConnectException : connect(..) failed: Address family not supported by protocol: /[5678:1234:eeee:aaaa:0000:eeee:aaaa:xxxx]:25565` (IP redacted)

Im not using any extra protocol plugins on the proxy, even if i do i still get the same error.

**Comment by MiniDigger** [comment]
remove the [ ], lol

**Comment by Janmm14** [comment]
but keep the quotes `"`, because yaml might not like the `:` unquoted

**Comment by Nacioszeczek** [comment]
IPv6 requires the brackets and quotes, `address: "[IP]:port"` would be the correct way,
I'll be closing this issue now, if you need further help feel free to ask on our [Discord](https://discord.gg/papermc).
