### ISSUE TITLE
Spigot 1.19.2 -> Client 1.20.2

### ISSUE THREAD

**Issue by Will33ELS** [WaterfallMC/Waterfall#815]
Waterfall version: git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0407ef5:537 by md_5

**Client error**

`[10:13:48] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: {\"text\":\"\u00A78\u00A7l[\u00A79\u00A7lH\u00A78\u00A7l]\u00A7r \u00A76Connexion sous compte premium effectu\u00E9e.\"}`

**Bug Description**
Hello, I'm encountering an issue with players on version 1.20.2. They are getting disconnected instantly upon joining.

**Steps to Reproduce**
Login with 1.20.2 client on Paper git-Paper-263 (MC: 1.19.2)

**Expected Behavior**
So that the player can connect.

**Comment by SrMonsterYT** [comment]
i'm having the same problem, i log into the server and it shows disconnected, i don't get console errors or anything, it just shows a disconnected message, i'm using the latest version of waterfall

**Comment by electronicboy** [comment]
This is likely down to the bungeecord issue relating to packet phases

**Comment by SrMonsterYT** [comment]
> This is likely down to the bungeecord issue relating to packet phases

so should I wait for a fix?

**Comment by Ceddix** [comment]
I'm still experiencing the bug atm. Is there any fix yet or does anyone have a link to the correct bug tracker?
