### ISSUE TITLE
Switching between servers does not update view distance [1.20.2]

### ISSUE THREAD

**Issue by BoomEaro** [WaterfallMC/Waterfall#819]
It seems that entity metadata rewrite does not work correctly for 1.20.2. 
Switching between servers does not update view distance if entity metadata rewrite has been enabled.

The solution seems to be to always send ClientSettings packet for 1.20.2:
https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0044-Provide-an-option-to-disable-entity-metadata-rewriti.patch#L68

**Comment by electronicboy** [comment]
This project is EOL, I've shoved through a hotfix, this appears to be an issue with how server switching is handled in general, but, I'm not wasting any more time on this.
