### ISSUE TITLE
Invalid signature for profile public key

### ISSUE THREAD

**Issue by ZeroOneJP** [WaterfallMC/Waterfall#820]
Hello people,

I currently cant run any server network without getting this bug.
Everytime I join I get kicked and the following error appears: "Invalid signature for profile public key"

I tried everything like enforce_secure_profile, other clients and stuff but nothing works.
Cant find a bug fix anywhere.

Does someone know what I can do?
Cheers
Felix

Proxy: Bungeecord 1.20 Server: Paper 1.20.1
Dedicated Server

**Comment by Janmm14** [comment]
Please use forums like [PaperMC](https://forums.papermc.io/) for such questions.

**Comment by electronicboy** [comment]
We don't touch the key, this is pretty much often down to janky clients or mojang services issues

**Comment by ZeroOneJP** [comment]
I have the solution.
Enable Bungeecord on the Minecraft Server and use ip forward on Bungeecord.
