### ISSUE TITLE
Switching servers causes view distance to drop

### ISSUE THREAD

**Issue by ghost** [WaterfallMC/Waterfall#821]
### Expected behavior

when you switch servers, your view distance should be the one in your options

### Observed/Actual behavior

server sets your render distance to I think 2, you need to open options screen then close it and then it updates, I think closing options screen sends another options packet.

### Steps/models to reproduce

on waterfall server, with 2 paper servers, switch from one to the other, your view distance gets set to 2 until you relog or open options menu.

### Plugin and Datapack List

Waterfall config:

throttling:
  tab_complete: 1000
log_initial_handler_connections: true
registered_plugin_channels_limit: 128
use_netty_dns_resolver: true
allow_empty_packets: false
game_version: "1.20.2"
disable_tab_list_rewrite: false
disable_entity_metadata_rewrite: true
disable_modern_tab_limiter: true
plugin_channel_name_limit: 128

### Paper version

This server is running Paper version git-Paper-"a2ba452" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: a2ba452)
You are running the latest version
Previous version: git-Paper-"29d1c7b" (MC: 1.20.1)

**Comment by electronicboy** [comment]
The aspect of switching servers would imply that this is not a paper issue, moving over to the waterfall tracker, but, given the nature of WF, the only real question is, have you tested with bungee?

**Comment by ghost** [comment]
> The aspect of switching servers would imply that this is not a paper issue, moving over to the waterfall tracker, but, given the nature of WF, the only real question is, have you tested with bungee?

I have never used bungee, apparently though this is an issue with the entity metadata rewrite, even though I have it disabled

https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0044-Provide-an-option-to-disable-entity-metadata-rewriti.patch#L68


https://github.com/PaperMC/Waterfall/issues/819

**Comment by ghost** [comment]
bump

**Comment by electronicboy** [comment]
This project is EOL, I've shoved through a hotfix, this appears to be an issue with how server switching is handled in general, but, I'm not wasting any more time on this.
