### ISSUE TITLE
Switching server causes client to disconnect

### ISSUE THREAD

**Issue by EpicJosch** [WaterfallMC/Waterfall#822]
Sometimes when switching server the client is being kicked from the network. This happens if the client sends playing packets while in config connection phase which was introduced a while ago. This happens most often on clients that need longer to connect and therefore are longer in config phase for example when I type /server <Server name> and move then. I'm being kicked from the whole network then and I receive a error message that tells me that the PlayerPositionChange Packet was unknown..

**Comment by electronicboy** [comment]
Have you tested this against bungeecord?

**Comment by EpicJosch** [comment]
You mean i should try it with the raw bungeecord?

**Comment by EpicJosch** [comment]
Tested it. Same problem on bungeecord.

**Comment by MattTheTekie** [comment]
I have the same issue.

**Comment by EpicJosch** [comment]
Not waterfalls issue. Apologize.
