### ISSUE TITLE
Unable to make field int java.awt.Color.value accessible

### ISSUE THREAD

**Issue by bolda500** [WaterfallMC/Waterfall#840]
I used build [559] before - no errors related to this issue.
After changing the version to the latest build [561] i get this issue: 

08.01 22:35:28 [Server] INFO com.google.gson.JsonIOException: Failed making field 'java.awt.Color#value' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
08.01 22:35:28 [Server] INFO at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:38) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:286) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.Gson.getAdapter(Gson.java:556) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.Gson.getAdapter(Gson.java:556) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.Gson.getAdapter(Gson.java:556) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1226) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1300) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:24) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1227) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:1300) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:211) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:30) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]
08.01 22:35:28 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[waterfall-1.20-561.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:945f1a3:561]

Debian: 11
Java: openjdk version "17.0.9" 2023-10-17

**Comment by BoomEaro** [comment]
Fixed in https://github.com/SpigotMC/BungeeCord/pull/3594
