### ISSUE TITLE
Mark this project as Public Archive because of EoL

### ISSUE THREAD

**Issue by mrjasonn** [WaterfallMC/Waterfall#848]
Tutorial: [https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)

**Comment by MiniDigger** [comment]
no. as said in the announcement, we may still do upstream updates from time to time.
there is a big warning in the readme, on our website, on our docs and when you run the build, thats gotta be enough for now.
