### ISSUE TITLE
How to fork waterfall?

### ISSUE THREAD

**Issue by SpigotRCE** [WaterfallMC/Waterfall#851]
When I am creating a intelij module of it, line 16 in pom.xml is giving me error, "Cannot resolve module". Also how to apply patches so it generates the src?

**Comment by electronicboy** [comment]
either you do it as a standard fork, or you look towards stuff like the travertine scripts

**Comment by SpigotRCE** [comment]
> either you do it as a standard fork, or you look towards stuff like the travertine scripts

I edited the desc please read it again

**Comment by electronicboy** [comment]
See the readme, you probably forgot to apply patches

**Comment by SpigotRCE** [comment]
umm i am on windows so like i cannot run .sh files


> See the readme, you probably forgot to apply patches

i am windows so i like cannot run .sh files

**Comment by MagicTeaMC** [comment]
try WSL

**Comment by Janmm14** [comment]
> umm i am on windows so like i cannot run .sh files
> 
> > See the readme, you probably forgot to apply patches
> 
> i am windows so i like cannot run .sh files

use git bash
