### ISSUE TITLE
[##########]<-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 030106f2010006ee03039d3b08adb495

### ISSUE THREAD

**Issue by dhyeyplayzde3** [WaterfallMC/Waterfall#854]
idk im using eaglercraft

**Comment by electronicboy** [comment]
An unexpected packet was sent during the login process, this is generally down to mods sending custom packets or something breaking the packet stream. Waterfall is no longer supported and with the state of my eye, I have little inclination to dig into such issues.

**Comment by MiniDigger** [comment]
try using a real minecraft client, not eaglercraft (which is also illegal and has been repeatedly struck down by mojang)
