### ISSUE TITLE
Problem when connected with last waterfall

### ISSUE THREAD

**Issue by DjeyMute** [WaterfallMC/Waterfall#855]
Hi,
I have this error with the last waterfall 582
I have 3 servers which are linked together.

09.12 12:29:33 [Server] ERROR [/90.48.146.93:57032|DjeyMute] -> UpstreamBridge - encountered exception
09.12 12:29:33 [Server] INFO io.netty.handler.codec.EncoderException: java.lang.NullPointerException
09.12 12:29:33 [Server] INFO at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134) ~[?:?]
09.12 12:29:33 [Server] INFO at me.neznamy.tab.platforms.bungeecord.BungeePipelineInjector$DeserializableBungeeChannelDuplexHandler.write(BungeePipelineInjector.java:217) ~[?:?]
09.12 12:29:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:891) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:956) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:982) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:950) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:969) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:310) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:103) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:161) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at net.md_5.bungee.UserConnection.lambda$sendPacketQueued$0(UserConnection.java:210) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfalljava17.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:9ab9e2b:582]
09.12 12:29:33 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
09.12 12:29:33 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by electronicboy** [comment]
1) This software is no longer supported
2) You're missing the actual causing exception

**Comment by DjeyMute** [comment]
But you make update of Waterfall so ?
If I give you the real error you Can fix thar or not ?

**Comment by electronicboy** [comment]
I did the update because I'm still using it myself, the software is still unsupported and will not be getting much attention from our organisation, as we've been warning for a long time now.

if you provide the actual causing error, maybe, but this project is no longer supported
